config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
  end

  root :to => 'admin/home#index'
  mount ShopifyApp::Engine, at: '/'

  namespace :admin do
    root 'quotations#index'
    #get "" => redirect("/admin/quotations")
    resources :quotations
    get '/billing', to: 'billing#index', as: 'billing'
    get '/billing/generate_invoice', to: 'billing#generate_invoice', as: 'generate_invoice'
    get '/settings', to: 'settings#index', as: 'settings'
    post '/settings/turnaround_multipliers', to: 'settings#turnaround_multipliers', as: 'turnaround_multipliers'
    post '/settings/volume_discounts', to: 'settings#volume_discounts', as: 'volume_discounts'
    post '/settings/product_variants', to: 'settings#product_variants', as: 'product_variants'
    get '/quotations_samples', to: 'quotations#samples', as: 'quotations_samples'
    get '/search', to: 'quotations#search_filter'

    # Customer
    get '/customers/account', to: 'customers#account', as: 'customer_account'
    post '/customers/account_update', to: 'customers#account_update', as: 'account_update'
    get '/customers/wallet', to: 'customers#wallet', as: 'customer_wallet'
    get '/customers/billing', to: 'customers#billing', as: 'customer_billing'
    get '/customers/templates', to: 'customers#templates', as: 'customer_templates'

    ## Temporary routes
    get '/pricing', to: 'pricing#index'
    get 'welcome/index'

    resources :articles do
      resources :comments
    end
    ## Temporary routes end
  end

#### Routes for customer portal
  get ENV['SHOPIFY_PROXY_PATH'], to: redirect(ENV['SHOPIFY_PROXY_PATH']+'/dashboard')

  scope ENV['SHOPIFY_PROXY_PATH']  do
    resources :articles do
      resources :comments
    end

    get '/dashboard', to: 'dashboard#index', as: 'dashboard'

    resources :quotations
    #resources :customers

    get     '/dashboard/new_order/:id',       to: 'dashboard#new_order',          as: 'new_order'
    get     '/dashboard/load_templates/:id',  to: 'dashboard#load_templates',     as: 'load_templates'
    get     '/dashboard/order/:token',        to: 'dashboard#order',              as: 'order'
    post    '/dashboard/draft/delete/:id',    to: 'dashboard#draft_order_delete', as: 'draft_order_delete'

    get     '/billing',                       to: 'billing#index',                as: 'billing'
    post    '/billing/generate/invoice',      to: 'billing#generate_invoice',     as: 'generate_invoice'
    get     '/billing/invoice/:token',        to: 'billing#invoice',              as: 'invoice'
    get     '/billing/invoice_print/:token',  to: 'billing#invoice_print',        as: 'invoice_print'

    get     '/settings',                      to: 'settings#index',               as: 'settings'
    post    '/update/settings',               to: 'settings#update',              as: 'settings_update'

    get     '/templates',                     to: 'templates#index',              as: 'templates'
    post    '/create/template',               to: 'templates#create',             as: 'create_template'
    delete  '/delete/template/:id',           to: 'templates#delete',             as: 'delete_template'
    put     '/update/template/:id',           to: 'templates#update',             as: 'update_template'
    post    '/save_image/template/:id',       to: 'templates#save_image',         as: 'save_template_image'
    delete  '/delete_image/template/:id',     to: 'templates#delete_image',       as: 'delete_template_image'
    # get     '/template/:id',                  to: 'templates#show',               as: 'show_template'

    get     '/cart',                          to: 'cart#index',                   as: 'cart'
    post    '/cart/create_order',             to: 'cart#create_order',            as: 'create_order'
    post    '/cart/wallet',                   to: 'cart#wallet',                  as: 'cart_wallet'

    get     'pricing/index'
    get     'pricing/need'
  end
#### Routes for customer portal end


  # Default route came with rails, have to check what to do with it.
  root 'welcome#index'
end

app/models/quotation.rb
class Quotation < ApplicationRecord
    belongs_to :yearly_quantity
    has_many :templates, dependent: :destroy
    validates :message, :quantity, :yearly_quantity_id,  presence: true
    validates_inclusion_of :resize_image, :in => [true, false]
    validates :quantity, numericality: { only_integer: true }
    validate :any_present?
    #validates_presence_of :image_width, :message => " Or Image height is required",  :if => :error_required_image_width?

    scope   :by_status, ->  (status) { where status: status }
    scope   :by_query, ->   (query)                 { where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%") }
    scope   :by_date, ->    (start_date, end_date)  { where("created_at >= ? AND created_at <= ?", start_date, end_date) }

    STATUS =['Status','new','ready','completed']


    def any_present?
        if resize_image == false || resize_image.nil?
            false
        else
          if %w(image_height image_width).all?{|attr| self[attr].blank?}
            errors.add :base, "You should input at-least one field of resizing \"Height\" or \"Width\" "
          end
        end
    end


    # def error_required_image_width?

    #   image_height_new = image_height.to_i == 0 ? 0 : image_height.to_i
    #   if resize_image == false || resize_image.nil?
    #         false
    #     else
    #         if resize_image == true && image_height_new > 0
    #             false
    #         else
    #             puts "height less than 0"
    #             return true
    #         end
    #     end
    # end

    def self.daterange_filter(start_date, end_date)
      where( "created_at >= ? AND created_at <= ?", start_date, end_date )
    end

    def self.query_filter(query)
      where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%")
    end

    def self.search_quotation(status, query, start_date, end_date)
      if start_date == nil
          self.where(status: status).query_filter(query)
      elsif query == nil
          self.where(status: status).daterange_filter(start_date, end_date)
      elsif status == nil
          self.where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%").daterange_filter(start_date, end_date)
      else
          self.where(status: status).query_filter(query).daterange_filter(start_date, end_date)
      end
    end

    def self.search(status, query, daterange)
        results = []

        if(daterange != "")
           start_date = Date.strptime(daterange.at(0..9), '%m/%d/%Y')
           end_date =  Date.strptime(daterange.at(13..22), '%m/%d/%Y')
        end

        case
          when (status != "Status" && query != "" && daterange != "") then
            results = search_quotation(status, query, start_date, end_date)

          when (status != "Status" && query == "" && daterange == "") then
            results = self.by_status(status)

          when (status == "Status" && query != "" && daterange == "") then
            results = self.by_query(query)

          when (status == "Status" && query == "" && daterange != "") then
            results = self.by_date(start_date, end_date)

          when (status != "Status" && query != "" && daterange == "") then
            results = search_quotation(status, query, nil, nil)

          when (status != "Status" && query == "" && daterange != "") then
            results = search_quotation(status, nil, start_date, end_date)

          when (status == "Status" && query != "" && daterange != "") then
            results = search_quotation(nil, query, start_date, end_date)

          when (status == "Status" && query == "" && daterange == "") then
            results = self.all
        end
        results

    end

end

app/controllers/admin/quotations_controller.rb
class Admin::QuotationsController < ShopifyApp::AuthenticatedController
  layout 'admin'

  def index
    @quotations = Quotation.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def new
    @path = "sumon"
  end

  def samples
    @folder_path = "quotation/"+params[:service]+"/"+params[:option]
    @images = Dir.glob("app/assets/images/"+@folder_path+"/*.jpg").sort
    render layout: false
  end

  def search_filter
    @quotations = Quotation.search(params[:filter], params[:search_box], params[:daterange_box]).order(updated_at: :desc).page(params[:page]).per(10)
    render :template => 'admin/quotations/index'
  end

end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  include ShopifyApp::AppProxyVerification
  include AppProxyAuth
  require 'json'
  require 'securerandom'

  def index

    unless is_user_logged_in
      redirect_to login_url and return
    end

    @quotations = Quotation.where(customer_id: logged_in_user_id).order(created_at: :desc)
    render layout: true, content_type: 'application/liquid'
  end

  def show
    @quotation = Quotation.where(:token =>params[:id]).select('*').first
    if @quotation.blank?
      not_found
    else
      @variants = []
      connect_to_shopify
      unless @quotation.product_variants.nil?
        JSON.parse(@quotation.product_variants).each do |v|
          product = ShopifyAPI::Product.find(v['product_id'])
          variants = product.variants
          variants.each do |vitem|
            vitem.product_id = vitem.product_id
          end
          @variants.concat variants
        end  
      end
      
      @turnaround = Turnaround.all
      
      logger.debug " variants: #{@variants.length}"
      
      @customer = ShopifyAPI::Customer.find(@quotation.customer_id)
      render layout: 'guest', content_type: 'application/liquid'
    end
  end

  def new
    @quotation = Quotation.new
    @customer = Customer.new
    render layout: 'guest', content_type: 'application/liquid'
  end

  def create
    @quotation = Quotation.new(quotation_params)

    if is_customer
      unless @quotation.valid?
        render_new_quotation
        return
      end
      customer_id = get_logged_in_customer_id
    else
      @customer = Customer.new(customer_params)
      unless @customer.valid? && @quotation.valid?
        render_new_quotation
        return
      end
      customer_id = get_customer_id_from_shopify
    end
    
    tf= Time.now
    time = Time.at(tf).utc.strftime('%Y-%m-%d %H:%M:%S')
    msec = tf.usec
    float_fraction_of_time = "."+ msec.to_s
    created_at = time + float_fraction_of_time

    token = Digest::MD5.hexdigest(created_at)

    customer_name = params[:customer][:first_name] + ' ' + params[:customer][:last_name]
    customer_email = params[:customer][:email]

    quotation_data = quotation_params.merge(
        customer_id: customer_id,
        customer_name: customer_name,
        customer_email: customer_email,
        token: token
    )

    connect_to_shopify
    @customer = ShopifyAPI::Customer.find(customer_id)
    @shop = ShopifyAPI::Shop.current
    shop_meta = @shop.metafields

    @quotation = Quotation.new(quotation_data)

    if @quotation.save
        #customer mail
        mailer =  QuotationMailer.send_quotation_received_for_customer(@customer, @shop, @quotation, shop_meta)
        mailer_response = mailer.deliver_now
        mailgun_message_id = mailer_response.message_id

        #admin mail
        admin_mailer =  QuotationMailer.quotation_receive_for_admin(@customer, @shop, @quotation, shop_meta)
        admin_mailer_response = admin_mailer.deliver_now
        admin_mailgun_message_id = admin_mailer_response.message_id

        redirect_to quotation_path(token)
    else
      render_new_quotation
    end

  end

  def edit
    @quotation = Quotation.find(params[:token])
  end

  def update
    @quotation = Quotation.find(params[:id])
    respond_to :html, :json
    if  @quotation.update_attributes(quotation_update_params)
      render :json => {
        file_content:  @quotation.message,
        file_error:  @quotation.errors,
        redirect: cart_url
      }
    else
      render :json => {
        file_content: @quotation.errors,
        status: :unprocessable_entity
      }
    end

  end

  private
    def get_customer_id_from_shopify
      connect_to_shopify
      customer = ShopifyAPI::Customer.search(query: 'email:'+params[:customer][:email])
      if customer.count >= 1
        return customer[0].id
      else
        return create_customer_at_shopify
      end
    end

  private
    def create_customer_at_shopify
      connect_to_shopify
      @customer = ShopifyAPI::Customer.new(customer_params.to_h)
      if @customer.save
        return @customer.id
      else
        render_new_quotation
        return
      end
    end

  private
    def quotation_params
      params.require(:quotation).permit(:message, :quantity, :yearly_quantity_id, :resize_image, :image_width, :image_height)
    end

  private
    def quotation_update_params
      params.require(:quotation).permit(:quantity, :return_file_format, :set_margin, :resize_image, :image_width, :image_height, :additional_comment, :product_variants, :total_price)
    end

  private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email)
    end

  private
    def is_customer
      params[:customer_id].present? && !params[:customer_id].blank? ? true : false
    end

  private
    def get_logged_in_customer_id
      return params[:customer_id]
    end

  private
    def render_new_quotation
      render layout: 'guest', action: 'new', content_type: 'application/liquid'
    end

end

app/views/admin/quotations/_search_form.html.erb
<%= form_tag admin_search_path, method: :get do %>
  <div class="input-group row">
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4 col-btn-search">
      <%= select_tag 'filter', options_for_select(Quotation::STATUS, params[:filter]), :class => "form-control" %>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-4 col-xs-4 col-field-search">
      <% if params[:daterange_box].nil? %>
        <%= text_field_tag :daterange_box, nil, :autocomplete => 'off', :placeholder => 'Date Range' ,  class: "form-control daterange" %>
      <% else %>
        <%= text_field_tag :daterange_box, params[:daterange_box], :autocomplete => 'off', :placeholder => 'Date range' ,  class: "form-control daterange" %>
      <% end %>  
    </div>  
    <div class="col-lg-5 col-md-3 col-sm-4 col-xs-4 col-field-search">
      <% if params[:search_box].nil? %>
        <%= text_field_tag :search_box, nil, :autocomplete => 'off', :placeholder => 'Q.ID, Customer Name, Email' ,  class: 'form-control' %>
      <% else %>
        <%= text_field_tag :search_box, params[:search_box], :autocomplete => 'off', :placeholder => 'Q.ID, Customer Name, Email' , class: 'form-control' %>
      <% end %>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1 col-btn-search">
      <%= submit_tag 'Search', :class => "btn btn-blue btnSearch" %>
    </div>
  </div>
<% end %>

app/views/admin/quotations/index.html.erb
<div class="container">

	<div class="page-header">
		<div class="row">
			<div class="col-lg-5 col-md-5 col-sm-4 col-xs-12">
				<h3 class="text-uppercase">QUOTATIONS</h3>
			</div>
			<div class="col-lg-7 col-md-7 col-sm-8 col-xs-11 col-searchform">
				<%= render '/admin/quotations/search_form' %>
			</div>
		</div>

	</div>

	<a href="<%=  new_admin_quotation_path %>">
	    <div class="btn btn-blue"><i class="entypo-plus"></i> NEW QUOTE</div>
	</a>
	<br>



	<div class="table-responsive">
		<table class="table table-striped">
		<thead>
			<tr>
				<th>Quotation No.</th>
				<th>Customer name</th>
				<th>Date</th>
				<th>Services</th>
				<th>Amount</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<% if @quotations != nil %>
				<% if @quotations.count > 0 %>
			        <% @quotations.each do |quotation| %>
			    		<tr>
			    			<td>#<%= link_to quotation.id, admin_quotation_path(quotation) %></td>
			    			<td><%= quotation.customer_name %></td>
			    			<td><%= quotation.created_at %></td>
			    			<td>
			    				<% unless quotation.product_variants.blank? %>
				    				<% services = [] %>
				    				<% JSON.parse(quotation.product_variants).each do |variant| %>
				    					<% services.push variant['title'] %>
				    				<% end %>
				    				<%= services.join(', ') %>
			    				<% end %>
			    			</td>
			    			<td><%= quotation.total_price %></td>
			    			<td><div class="label label-info"><%= quotation.status %></div></td>
			    		</tr>
					<% end %>
				<% else %>
					<tr><td colspan="6"><p>No Recod Found</p></td></tr>
			    <% end %>
			<% else %>
				<tr>
					<td colspan="6">
						<p>No Recod Found</p>
					</td>
				</tr>
			<% end %>

		</tbody>
	</table>
	</div>

	<%= paginate @quotations if @quotations %>
</div>

app/views/admin/quotations/new.html.erb
<div class="container">
	<div class="page-header">
		<h3>CREATE NEW QUOTATION</h3>
	</div>

	<%= render 'form' %>

</div>

<!-- Modal 1 (Basic)-->
<div class="modal fade" id="modal-more-samples">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">More samples to help you choose the right option.</h4>
			</div>

			<div class="modal-body">

			</div>

		</div>
	</div>
</div>

app/views/admin/quotations/samples.erb
<% @images.each do |image| %>
    <%
        full_image_name = image.split('/').last
        last_part = full_image_name.split('_').last
        full_image_name.slice! last_part
        first_part = full_image_name
    %>

    <% unless last_part == 'before.jpg' %>
        	<div class="col-xs-6 after more_sample_image">
        		<%= image_tag(@folder_path+"/#{image.split('/').last}", class: "img-thumbnail img-responsive after") %>
            	<div class="col-xs-12 before">
            		<%= image_tag(@folder_path+"/"+first_part+"before.jpg", class: "img-thumbnail img-responsive") %>
            	</div>
        	</div>
    	</div>
	<% end %>

<% end %>