config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
  end

  root :to => 'admin/home#index'
  mount ShopifyApp::Engine, at: '/'

  namespace :admin do
    root 'quotations#index'
    #get "" => redirect("/admin/quotations")
    resources :quotations
    get '/billing', to: 'billing#index', as: 'billing'
    get '/billing/generate_invoice', to: 'billing#generate_invoice', as: 'generate_invoice'
    get '/settings', to: 'settings#index', as: 'settings'
    post '/settings/turnaround_multipliers', to: 'settings#turnaround_multipliers', as: 'turnaround_multipliers'
    post '/settings/volume_discounts', to: 'settings#volume_discounts', as: 'volume_discounts'
    post '/settings/product_variants', to: 'settings#product_variants', as: 'product_variants'
    get '/quotations_samples', to: 'quotations#samples', as: 'quotations_samples'
    get '/search', to: 'quotations#search_filter'

    # Customer
    get '/customers/account', to: 'customers#account', as: 'customer_account'
    post '/customers/account_update', to: 'customers#account_update', as: 'account_update'
    get '/customers/wallet', to: 'customers#wallet', as: 'customer_wallet'
    get '/customers/billing', to: 'customers#billing', as: 'customer_billing'
    get '/customers/templates', to: 'customers#templates', as: 'customer_templates'

    ## Temporary routes
    get '/pricing', to: 'pricing#index'
    get 'welcome/index'

    resources :articles do
      resources :comments
    end
    ## Temporary routes end
  end

#### Routes for customer portal
  get ENV['SHOPIFY_PROXY_PATH'], to: redirect(ENV['SHOPIFY_PROXY_PATH']+'/dashboard')

  scope ENV['SHOPIFY_PROXY_PATH']  do
    resources :articles do
      resources :comments
    end

    get '/dashboard', to: 'dashboard#index', as: 'dashboard'

    resources :quotations
    #resources :customers

    get     '/dashboard/new_order/:id',       to: 'dashboard#new_order',          as: 'new_order'
    get     '/dashboard/load_templates/:id',  to: 'dashboard#load_templates',     as: 'load_templates'
    get     '/dashboard/order/:token',        to: 'dashboard#order',              as: 'order'
    post    '/dashboard/draft/delete/:id',    to: 'dashboard#draft_order_delete', as: 'draft_order_delete'

    get     '/billing',                       to: 'billing#index',                as: 'billing'
    post    '/billing/generate/invoice',      to: 'billing#generate_invoice',     as: 'generate_invoice'
    get     '/billing/invoice/:token',        to: 'billing#invoice',              as: 'invoice'
    get     '/billing/invoice_print/:token',  to: 'billing#invoice_print',        as: 'invoice_print'

    get     '/settings',                      to: 'settings#index',               as: 'settings'
    post    '/update/settings',               to: 'settings#update',              as: 'settings_update'

    get     '/templates',                     to: 'templates#index',              as: 'templates'
    post    '/create/template',               to: 'templates#create',             as: 'create_template'
    delete  '/delete/template/:id',           to: 'templates#delete',             as: 'delete_template'
    put     '/update/template/:id',           to: 'templates#update',             as: 'update_template'
    post    '/save_image/template/:id',       to: 'templates#save_image',         as: 'save_template_image'
    delete  '/delete_image/template/:id',     to: 'templates#delete_image',       as: 'delete_template_image'
    # get     '/template/:id',                  to: 'templates#show',               as: 'show_template'

    get     '/cart',                          to: 'cart#index',                   as: 'cart'
    post    '/cart/create_order',             to: 'cart#create_order',            as: 'create_order'
    post    '/cart/wallet',                   to: 'cart#wallet',                  as: 'cart_wallet'

    get     'pricing/index'
    get     'pricing/need'
  end
#### Routes for customer portal end


  # Default route came with rails, have to check what to do with it.
  root 'welcome#index'
end

app/controllers/admin/billing_controller.rb
class Admin::BillingController < ShopifyApp::AuthenticatedController
    layout 'admin'

    def index

    end

    def generate_invoice
        #puts params.inspect
        render "index"
    end

end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
    include ShopifyApp::AppProxyVerification
    include AppProxyAuth
    layout "print", only: [:invoice_print]
    def index

        unless is_user_logged_in
            redirect_to login_url and return
        end

        connect_to_shopify

        wallets = Wallet.where(:customer_id => logged_in_user_id)
        if wallets.empty?
            @wallet_balance = 0
        else
            @wallet_balance = wallets.last.wallet_balance
        end
     
        @product = ShopifyAPI::Product.find(:all, params: { :product_type => 'Credit bundle' }).first.attributes
        
        @uninvoiced_draft_orders = []
        draft_orders = ShopifyAPI::DraftOrder.where( :customer => { :id => logged_in_user_id })
        draft_orders.sort! {|x,y| y.created_at <=> x.created_at }
        
        draft_orders.each do |draft_order|
            if draft_order.tags.include?('Invoice') and (( draft_order.status == 'open' ) or ( draft_order.status == 'invoice_sent'))
                @uninvoiced_draft_orders.push draft_order
            end
        end
        
        render layout: true, content_type: 'application/liquid'

    end
    
    def invoice
        render layout: true, content_type: 'application/liquid'
    end
    
    def invoice_print
        @print = true
        render layout: true, action: 'invoice', content_type: 'application/liquid'
    end

    def generate_invoice
        order_names ||= params[:order_names]
        customer    ||= params[:customer]
        line_items  = []
        orders      = []
        
        respond_to :html, :json
        unless order_names.nil?
        
            connect_to_shopify
            order_names.each do |order_name|
                order       = ShopifyAPI::Order.where(:name => order_name).first
                orders.push order
                
                line_items.push ShopifyAPI::LineItem.new(   
                                                            :custom     => true,
                                                            :price      => order.subtotal_price,
                                                            :quantity   => 1,  
                                                            :title      => order.name,
                                                            :tax_lines  => order.tax_lines,
                                                            :properties => [{
                                                                :name   => 'order_id',
                                                                :value  => order.id
                                                            }]
                                                            )
            end
            
            draft_order = ShopifyAPI::DraftOrder.new(
                                                      :line_items                   => line_items,
                                                      :customer                     => { :id => customer },
                                                      :use_customer_default_address => true,
                                                      :tags                         => 'Invoice'
                                                    )
            
            if draft_order.save
                
                orders.each do |order|
                    tags        = order.tags 
                    order.tags  = tags.gsub('Unpaid', 'Invoiced')
                    order.save
                end
                
                draft_data                  = {}
                draft_data[:name]           = draft_order.name
                draft_data[:created_at]     = Date.parse(draft_order.created_at).strftime('%d %B %Y')
                draft_data[:total_price]    = "$#{'%.02f' % draft_order.total_price}"
                draft_data[:status]         = draft_order.status
                draft_data[:invoice_url]    = draft_order.invoice_url
                
                render :json => {
                    status: 'success',
                    result: "Invoice for #{draft_order.name} was successfully generated!",
                    draft:  draft_data
                  }
            else
                render :json => {
                    status: 'error',
                    message: 'Internal Server Error!'
                  }
            end
              
        else
            
            render :json => {
                status: 'error',
                message:  'There should be at least 1 order checked.' 
              }
              
        end
        
    end

end

app/views/billing/_modal_account_type.html.erb
<!-- Modal 1 (Modal account type)-->
<div class="modal fade" id="modal-1">
	<div class="modal-dialog">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Available account types</h4>
			</div>
            
			<div class="modal-body">
			    <h5><b>Pay as you go</b></h5>
                <p>With the “Pay as you go account” you will be asked to pay at checkout for every order you place. Payment can be done via PayPal or by credit card and card detail is optionally saved from order to order to make it as easy as possible for you to pay.<br><br>
                
                Pay as you go is the default account level. All you need is a PayPal account and/or a credit card and you are ready to place your first order.</p><br>
                
                <h5><b>Pay as you go - with Wallet</b></h5>
                <p>With the “Pay as you go – with Wallet” you have an added wallet option to your pay as you go option. The wallet is used to deposit an appropriate amount of credit so you don’t have to use your credit card every time you place an order – simply use credits from your wallet.<br><br>
                
                Pay as you go – with Wallet is an added service that is free to use and provides great freedom to place an order anytime for the corporate user who do not want to use a credit card for every order.</p><br>
                
                <h5><b>Corporate monthly billing</b></h5>
                <p>With the “Corporate monthly billing account”, we will accommodate all your editing needs without you having to pay every time you check out. With the corporate monthly billing we collect and place all of your orders on one monthly invoice at the end of the month.<br><br>
                
                By having a Corporate monthly billing account you always have available access to getting images edited without having to spend time on paying with credit cards on each individual order – simply place the order and pay for all at the end of month.</p>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
			</div>
		</div>
	</div>
</div>

app/views/billing/index.html.erb
<div class="page-header">
	<h3 class="text-uppercase">BILLING</h3>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default panel-shadow" data-collapsed="0">

			<!-- panel head -->
			<div class="panel-heading">
				<div class="panel-title">ACCOUNT AND WALLET</div>
			</div>
			<!-- panel body -->
			<div class="panel-body">

				<h3 class="text-center">My account: Pay as you go</h3>
				<br>

				<form class="form-inline">
			        <div class="row">

						<div class="col-md-6">
							<label for="article_top_up"  class=" hidden-xs">&nbsp;</label>
							<h4 class="text-center">My Wallet balance: {{ <%= @wallet_balance*100 %> | money }}</h4>
							<br>
					    </div>
	                    <div class="col-md-6">
	                    	<div class="row">
	                    		<div class="col-md-8">
	                    			<div class='col-sm-5 text-center' >
			                    		<label>Top-Up</label><br>
			                           	<select class="form-control top-up-bundles" name="article[top_up]" id="article_top_up">
											<% for variant in @product[:variants] %>
											<option value="<%= variant.id %>"><%= variant.title %></option>
											<% end %>
										</select>
										<br>
									</div>

									<div class="input-spinner col-sm-7 text-center">
										<%= label_tag 'quantity', 'Quantity'  %><br>
										<div id="quantity">
											<%= button_tag('-', type: 'button', class: "btn btn-default", name:"button-qtn-l", id:"button-qtn-l") %>
											<input type="text" class="form-control size-1 top-up-number" value="1" data-min="1" data-max="20" data-validate="number,required">
											<%= button_tag('+', type: 'button', class: "btn btn-default", name:"button-qtn-l", id:"button-qtn-r")   %>
										</div>
										<br><br>
									</div>
	                    		</div>
	                    		<div class="col-md-4 text-center">
						            <!--<button type="button" class="btn btn-blue submit">Pay</button>-->
				                	<label for="article_top_up" style='display:block;' class="hidden-xs">&nbsp;</label>
				                    <input type="button" name="commit" value="TOP-UP <%= @product[:variants].first.title %>" class="btn btn-blue submit top-up-total" data-disable-with="Pay " id="pay-top-up-btn">
					            </div>
							</div>
			        	</div>
			        </div>
			    </form>

			    <div class="help-block"></div>

			    <div class="text-center">
			    	<p><%= mail_to 'info@clippingpathindia.com', "Apply for monthly billing account", subject: "Request for corporate monthly billing account" %></p>
				</div>

			    <div class="text-right">
			        <p>See all accont types <%= link_to 'here', '#', 'data-toggle': "modal", 'data-target': "#modal-1"  %></p>
				</div>

			</div>

		</div>
	</div>
</div>

<hr />

<div class="row">
	<div class="col-md-12">
		<h4>UNINVOICED ORDERS</h4>
		<p>We invoice you every end of the month. However if you wish you can also generate invoice yourself and pay.</p>
		<table class="table table-striped">
			<thead>
				<tr>
				    <th>
		    			<div class="checkbox checkbox-replace">
		    				<input type="checkbox" id="check-all-unvoiced">
		    			</div>
		    		</th>
					<th>Order No.</th>
					<th>Order date</th>
					<th>Quantity</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody id="unvoiced_body">
			    {% assign count = 0 %}
			    {% for order in customer.orders %}
			        {% if order.financial_status == 'paid' and order.tags contains 'Unpaid' and order.cancelled == false  %}
				        {% assign count = 1 %}
				        {% capture order_url %}
							<%= order_path('xxx') %>
						{% endcapture %}
						{% assign customer_url = order.customer_url | split: '/' %}
						{% assign token = customer_url.last %}
    				<tr>
    					<td>
    						<div class="checkbox checkbox-replace">
    							<input type="checkbox" class="unvoiced-individual-check">
    						</div>
    					</td>
    					<td class="unvoiced-order-name">
    						<a href="{{order_url | replace: 'xxx', token }}">{{ order.name }}</a>
    					</td>
    					<td>{{ order.created_at | date: "%d %B %Y" }}</td>
    					<td>{{ order.line_items.first.quantity }}</td>
    					<td>{{ order.total_price | money }}</td>
    				</tr>
    				{% endif %}
				{% endfor %}
				{% if count == 0 %}
				    <tr>
				        <td cols="5">No order found</td>
				    </tr>
				{% endif %}
			</tbody>
		</table>
		<div class="alert alert-info" id="generate_invoice_result"></div>
		<button id="generate_invoice" class="btn btn-blue text-uppercase" data-customer="{{customer.id}}" data-url="<%= generate_invoice_path %>">
		    GENERATE INVOICE
		</button>
	</div>
</div>

<hr />

<div class="row">
	<div class="col-md-12">
		<h4>OUTSTANDING INVOICES</h4>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Invoice No.</th>
					<th>Date</th>
					<th>Amount</th>
					<th>Status</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody id="invoice_table">

			    <% unless @uninvoiced_draft_orders.empty? %>
    			    <% @uninvoiced_draft_orders.each do |draft_order| %>

			            <tr>
        					<td><%= draft_order.name %></td>
        					<td><%= Date.parse(draft_order.created_at).strftime('%d %B %Y') %></td>
        					<td><%= "$#{'%.02f' % draft_order.total_price}" %></td>
        					<td>
        					    <% if draft_order.status == 'invoice_sent' %>
        					        <div class="label label-secondary text-uppercase">
            					        <%= draft_order.status.gsub('_', ' ') %>
            					    </div>
        					    <% elsif draft_order.status == 'open' %>
        					        <div class="label label-success text-uppercase">
            					        <%= draft_order.status.gsub('_', ' ') %>
            					    </div>
        					    <% end %>
        					</td>
        					<td>
        					    <a href="<%= draft_order.invoice_url %>" target="blank" class="btn btn-blue">PAY</a>
        					</td>
        				</tr>

    			    <% end %>
			    <% else %>

			        <tr id="invoice_empty_row" >
			            <td cols="5">
			                No invoice found
			            </td>
			        </tr>

			    <% end %>

			</tbody>
		</table>
	</div>
</div>

<hr />

<div class="row">
	<div class="col-md-12">
		<h4>BILLING HISTORY</h4>
	{% paginate customer.orders by 12 %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Date</th>
					<th>Details</th>
					<th>Amount</th>
				</tr>
			</thead>
			<tbody>
				{% for order in customer.orders %}
					{% unless order.tags contains 'Unpaid' or order.tags contains 'Invoiced' or order.cancelled %}
						{% capture order_url %}
							<%= order_path('xxx') %>
						{% endcapture %}
						{% assign customer_url = order.customer_url | split: '/' %}
						{% assign token = customer_url.last %}
						<tr>
							<td>{{ order.created_at | date: "%d %B %y" }}</td>
							<td>
								<a href="{{order_url | replace: 'xxx', token }}">
									{% if order.tags contains 'Paid from Wallet' %}
										ORDER {{ order.name }} ( Paid from Wallet: -{{ order.total_price | money }} )
									{% elsif order.tags contains 'Partially paid from Wallet' %}
										ORDER {{ order.name }} ( Partially paid from Wallet: -{{ order.discounts.first.amount | money }} )
									{% elsif order.line_items.first.sku contains 'CREDIT_' %}
										WALLET TOP-UP {{ order.name }}
									{% else %}
										ORDER {{ order.name }}
									{% endif %}
								</a>
							</td>
							{% if order.line_items.first.sku contains 'CREDIT_' %}
								<td class='text-success'>+{{ order.total_price | money }}</td>
							{% else %}
								<td class='text-info'>{{ order.total_price | money }}</td>
							{% endif %}
						</tr>
					{% endunless %}
				{% endfor %}
			</tbody>
		</table>
		
		<ul class="pager pull-left">
			{% if paginate.previous.is_link %}
			    <li><a href="{{ paginate.previous.url }}"><i class="entypo-left-thin"></i> {{ paginate.previous.title }}</a></li>
			{% endif %}
			{% if paginate.next.is_link %}
			    <li><a href="{{ paginate.next.url }}">{{ paginate.next.title }} <i class="entypo-right-thin"></i></a></li>
			{% endif %}
		</ul>
	{% endpaginate %}
	
	</div>
</div>

<%= render 'modal_account_type' %>

app/views/billing/invoice.html.erb
{% if customer %}

<div class="invoice">

	<div class="row">
	
		<div class="col-sm-6 invoice-left">
		
			<%= image_tag("clipping-path-india-logo-dark.png", :alt => "Clipping Path India Logo", :class => 'logo') %>
			
		</div>
		
		<div class="col-sm-6 invoice-right">
		       
                {% for order in customer.orders %}
                    {% if order.customer_url contains '<%= params[:token] %>' %}
                      {% assign corder = order %}
                    {% endif %}
                {% endfor %}
                
				<h3>
				    INVOICE NO. {{ corder.name }}
                </h3>
				<span>{{corder.created_at | date: "%d %B %Y" }}</span>
		</div>
		
	</div>
	
	<hr class="margin" />
	

	<div class="row">
	
		<div class="col-sm-3 invoice-left">
		
			<h4>Client</h4>
			    {{ corder.customer.name }}
			<br />
			    {{ corder.customer.addresses.first.company }}
			
		</div>
	
		<div class="col-sm-3 invoice-left">
			 
			<h4>&nbsp;</h4>
			    {{ corder.customer.addresses.first.address1 }}, {{ corder.customer.addresses.first.address2 }}
		    <br />
		        {{ corder.customer.addresses.first.city }}, {{ corder.customer.addresses.first.zip }}
	        <br />
		        {{ corder.customer.addresses.first.country }}
			<br />
			    {{ corder.customer.addresses.first.phone }}
		</div>
		
	</div>
	
	<div class="margin"></div>
	
	<table class="table table-bordered">
		<thead>
			<tr>
				<th class="text-center">#</th>
				<th width="50%">Service</th>
				<th>Unit price</th>
				<th>Quantity</th>
				<th>Total</th>
			</tr>
		</thead>
		
		<tbody>
		    <span style="display: none;">{% increment no %}</span>
		    {% for line_item in corder.line_items %}
                <tr>
					<td class="text-center">{% increment no %}</td>
					<td>{{ line_item.title }}</td>
					<td>{{ line_item.price | money }}</td>
					<td>{{ line_item.quantity }}</td>
					<td class="text-right">{{ line_item.line_price | money }}</td>
				</tr>
            {% endfor %}
		</tbody>
	</table>
	
	<div class="margin"></div>

	<div class="row">
	
		<div class="col-sm-6">
		
			<div class="invoice-left">
	
				{{ shop.address.company }}
				<br />
				{{ shop.address.street }}
				<br />
				{{ shop.address.city }}
				<br />
				{{ shop.address.zip }}
				<br />
				{{ shop.address.phone }}
				<br />
				<br />
				<div class="small">Clipping Path India is a brand of {{ shop.address.company }} Company registered in England and Wales. Registration No: 06815610</div>
			</div>
		
		</div>
		
		<div class="col-sm-6">
			
			<div class="invoice-right">
				
				<ul class="list-unstyled">
					{% assign total_discount = 0 %}
				     {% for discount in Corder.discounts %}
                        {% capture total_discount %}
                            {{ total_discount | plus: discount.saving }}
                        {% endcapture %}
                     {% endfor %}
                     
                    {% if total_discount == 0 and corder.tax_price == 0 %}
                        <li>
    						<h4>Total: {{ corder.total_price | money }}</h4>
    					</li>
    				{% endif %}
                    {% if total_discount > 0 and corder.tax_price == 0 %}
                        <li>
    						Sub-total: 
    						<strong>{{ corder.subtotal_price | money }}</strong>
    					</li>
                        <li>
    						Discount: 
    						<strong>
                                 -{{ total_discount | money }}
                            </strong>
    					</li>
    					<li>
    						<h4>Total: {{ corder.total_price | money }}</h4>
    					</li>
    				{% endif %}
                    {% if total_discount > 0 and corder.tax_price > 0 %}
                        <li>
    						Sub-total: 
    						<strong>{{ corder.subtotal_price | money }}</strong>
    					</li>
                        <li>
    						Discount: 
    						<strong>
                                 -{{ total_discount | money }}
                            </strong>
    					</li>
    					<!-- Show VAT only if VAT was charged -->
    					<li>
    						VAT (20%): 
    						<strong>{{ corder.tax_price | money }}</strong>
    					</li>
    					<li>
    						<h4>Total: {{ corder.total_price | money }}</h4>
    					</li>
                    {% endif %}
				</ul>
				
				<% unless @print %>
					<br />
					
					<a target="_blank" href="<%= invoice_print_url(params[:token]) %>" class="btn btn-primary btn-icon icon-left hidden-print">
						Print Invoice
						<i class="entypo-doc-text"></i>
					</a>
				<% end %>
			</div>
			
		</div>
		
	</div>

</div>

{% else %}
	<script>window.location.href = '/account/login';</script>
{% endif %}