config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'customers/index'
  end

  root :to => 'admin/home#index'
  mount ShopifyApp::Engine, at: '/'

  namespace :admin do
    root 'quotations#index'
    #get "" => redirect("/admin/quotations")
    resources :quotations
    get '/billing', to: 'billing#index', as: 'billing'
    get '/billing/generate_invoice', to: 'billing#generate_invoice', as: 'generate_invoice'
    get '/settings', to: 'settings#index', as: 'settings'
    post '/settings/turnaround_multipliers', to: 'settings#turnaround_multipliers', as: 'turnaround_multipliers'
    post '/settings/volume_discounts', to: 'settings#volume_discounts', as: 'volume_discounts'
    post '/settings/product_variants', to: 'settings#product_variants', as: 'product_variants'
    get '/quotations_samples', to: 'quotations#samples', as: 'quotations_samples'
    get '/search', to: 'quotations#search_filter'

    # Customer
    get '/customers/account', to: 'customers#account', as: 'customer_account'
    post '/customers/account_update', to: 'customers#account_update', as: 'account_update'
    get '/customers/wallet', to: 'customers#wallet', as: 'customer_wallet'
    get '/customers/billing', to: 'customers#billing', as: 'customer_billing'
    get '/customers/templates', to: 'customers#templates', as: 'customer_templates'

    ## Temporary routes
    get '/pricing', to: 'pricing#index'
    get 'welcome/index'

    resources :articles do
      resources :comments
    end
    ## Temporary routes end
  end

#### Routes for customer portal
  get ENV['SHOPIFY_PROXY_PATH'], to: redirect(ENV['SHOPIFY_PROXY_PATH']+'/dashboard')

  scope ENV['SHOPIFY_PROXY_PATH']  do
    resources :articles do
      resources :comments
    end

    get '/dashboard', to: 'dashboard#index', as: 'dashboard'

    resources :quotations
    #resources :customers

    get     '/dashboard/new_order/:id',       to: 'dashboard#new_order',          as: 'new_order'
    get     '/dashboard/load_templates/:id',  to: 'dashboard#load_templates',     as: 'load_templates'
    get     '/dashboard/order/:token',        to: 'dashboard#order',              as: 'order'
    post    '/dashboard/draft/delete/:id',    to: 'dashboard#draft_order_delete', as: 'draft_order_delete'

    get     '/billing',                       to: 'billing#index',                as: 'billing'
    post    '/billing/generate/invoice',      to: 'billing#generate_invoice',     as: 'generate_invoice'
    get     '/billing/invoice/:token',        to: 'billing#invoice',              as: 'invoice'
    get     '/billing/invoice_print/:token',  to: 'billing#invoice_print',        as: 'invoice_print'

    get     '/settings',                      to: 'settings#index',               as: 'settings'
    post    '/update/settings',               to: 'settings#update',              as: 'settings_update'

    get     '/templates',                     to: 'templates#index',              as: 'templates'
    post    '/create/template',               to: 'templates#create',             as: 'create_template'
    delete  '/delete/template/:id',           to: 'templates#delete',             as: 'delete_template'
    put     '/update/template/:id',           to: 'templates#update',             as: 'update_template'
    post    '/save_image/template/:id',       to: 'templates#save_image',         as: 'save_template_image'
    delete  '/delete_image/template/:id',     to: 'templates#delete_image',       as: 'delete_template_image'
    # get     '/template/:id',                  to: 'templates#show',               as: 'show_template'

    get     '/cart',                          to: 'cart#index',                   as: 'cart'
    post    '/cart/create_order',             to: 'cart#create_order',            as: 'create_order'
    post    '/cart/wallet',                   to: 'cart#wallet',                  as: 'cart_wallet'

    get     'pricing/index'
    get     'pricing/need'
  end
#### Routes for customer portal end


  # Default route came with rails, have to check what to do with it.
  root 'welcome#index'
end

app/models/quotation.rb
class Quotation < ApplicationRecord
    belongs_to :yearly_quantity
    has_many :templates, dependent: :destroy
    validates :message, :quantity, :yearly_quantity_id,  presence: true
    validates_inclusion_of :resize_image, :in => [true, false]
    validates :quantity, numericality: { only_integer: true }
    validate :any_present?
    #validates_presence_of :image_width, :message => " Or Image height is required",  :if => :error_required_image_width?

    scope   :by_status, ->  (status) { where status: status }
    scope   :by_query, ->   (query)                 { where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%") }
    scope   :by_date, ->    (start_date, end_date)  { where("created_at >= ? AND created_at <= ?", start_date, end_date) }

    STATUS =['Status','new','ready','completed']


    def any_present?
        if resize_image == false || resize_image.nil?
            false
        else
          if %w(image_height image_width).all?{|attr| self[attr].blank?}
            errors.add :base, "You should input at-least one field of resizing \"Height\" or \"Width\" "
          end
        end
    end


    # def error_required_image_width?

    #   image_height_new = image_height.to_i == 0 ? 0 : image_height.to_i
    #   if resize_image == false || resize_image.nil?
    #         false
    #     else
    #         if resize_image == true && image_height_new > 0
    #             false
    #         else
    #             puts "height less than 0"
    #             return true
    #         end
    #     end
    # end

    def self.daterange_filter(start_date, end_date)
      where( "created_at >= ? AND created_at <= ?", start_date, end_date )
    end

    def self.query_filter(query)
      where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%")
    end

    def self.search_quotation(status, query, start_date, end_date)
      if start_date == nil
          self.where(status: status).query_filter(query)
      elsif query == nil
          self.where(status: status).daterange_filter(start_date, end_date)
      elsif status == nil
          self.where("id = ? OR customer_name LIKE ? OR customer_email LIKE ?", "%"+query+"%", "%"+query+"%", "%"+query+"%").daterange_filter(start_date, end_date)
      else
          self.where(status: status).query_filter(query).daterange_filter(start_date, end_date)
      end
    end

    def self.search(status, query, daterange)
        results = []

        if(daterange != "")
           start_date = Date.strptime(daterange.at(0..9), '%m/%d/%Y')
           end_date =  Date.strptime(daterange.at(13..22), '%m/%d/%Y')
        end

        case
          when (status != "Status" && query != "" && daterange != "") then
            results = search_quotation(status, query, start_date, end_date)

          when (status != "Status" && query == "" && daterange == "") then
            results = self.by_status(status)

          when (status == "Status" && query != "" && daterange == "") then
            results = self.by_query(query)

          when (status == "Status" && query == "" && daterange != "") then
            results = self.by_date(start_date, end_date)

          when (status != "Status" && query != "" && daterange == "") then
            results = search_quotation(status, query, nil, nil)

          when (status != "Status" && query == "" && daterange != "") then
            results = search_quotation(status, nil, start_date, end_date)

          when (status == "Status" && query != "" && daterange != "") then
            results = search_quotation(nil, query, start_date, end_date)

          when (status == "Status" && query == "" && daterange == "") then
            results = self.all
        end
        results

    end

end

app/controllers/admin/quotations_controller.rb
class Admin::QuotationsController < ShopifyApp::AuthenticatedController
  layout 'admin'

  def index
    @quotations = Quotation.all.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def new
    @path = "sumon"
  end

  def samples
    @folder_path = "quotation/"+params[:service]+"/"+params[:option]
    @images = Dir.glob("app/assets/images/"+@folder_path+"/*.jpg").sort
    render layout: false
  end

  def search_filter
    @quotations = Quotation.search(params[:filter], params[:search_box], params[:daterange_box]).order(updated_at: :desc).page(params[:page]).per(10)
    render :template => 'admin/quotations/index'
  end

end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  include ShopifyApp::AppProxyVerification
  include AppProxyAuth
  require 'json'
  require 'securerandom'

  def index

    unless is_user_logged_in
      redirect_to login_url and return
    end

    @quotations = Quotation.where(customer_id: logged_in_user_id).order(created_at: :desc)
    render layout: true, content_type: 'application/liquid'
  end

  def show
    @quotation = Quotation.where(:token =>params[:id]).select('*').first
    if @quotation.blank?
      not_found
    else
      @variants = []
      connect_to_shopify
      unless @quotation.product_variants.nil?
        JSON.parse(@quotation.product_variants).each do |v|
          product = ShopifyAPI::Product.find(v['product_id'])
          variants = product.variants
          variants.each do |vitem|
            vitem.product_id = vitem.product_id
          end
          @variants.concat variants
        end  
      end
      
      @turnaround = Turnaround.all
      
      logger.debug " variants: #{@variants.length}"
      
      @customer = ShopifyAPI::Customer.find(@quotation.customer_id)
      render layout: 'guest', content_type: 'application/liquid'
    end
  end

  def new
    @quotation = Quotation.new
    @customer = Customer.new
    render layout: 'guest', content_type: 'application/liquid'
  end

  def create
    @quotation = Quotation.new(quotation_params)

    if is_customer
      unless @quotation.valid?
        render_new_quotation
        return
      end
      customer_id = get_logged_in_customer_id
    else
      @customer = Customer.new(customer_params)
      unless @customer.valid? && @quotation.valid?
        render_new_quotation
        return
      end
      customer_id = get_customer_id_from_shopify
    end
    
    tf= Time.now
    time = Time.at(tf).utc.strftime('%Y-%m-%d %H:%M:%S')
    msec = tf.usec
    float_fraction_of_time = "."+ msec.to_s
    created_at = time + float_fraction_of_time

    token = Digest::MD5.hexdigest(created_at)

    customer_name = params[:customer][:first_name] + ' ' + params[:customer][:last_name]
    customer_email = params[:customer][:email]

    quotation_data = quotation_params.merge(
        customer_id: customer_id,
        customer_name: customer_name,
        customer_email: customer_email,
        token: token
    )

    connect_to_shopify
    @customer = ShopifyAPI::Customer.find(customer_id)
    @shop = ShopifyAPI::Shop.current
    shop_meta = @shop.metafields

    @quotation = Quotation.new(quotation_data)

    if @quotation.save
        #customer mail
        mailer =  QuotationMailer.send_quotation_received_for_customer(@customer, @shop, @quotation, shop_meta)
        mailer_response = mailer.deliver_now
        mailgun_message_id = mailer_response.message_id

        #admin mail
        admin_mailer =  QuotationMailer.quotation_receive_for_admin(@customer, @shop, @quotation, shop_meta)
        admin_mailer_response = admin_mailer.deliver_now
        admin_mailgun_message_id = admin_mailer_response.message_id

        redirect_to quotation_path(token)
    else
      render_new_quotation
    end

  end

  def edit
    @quotation = Quotation.find(params[:token])
  end

  def update
    @quotation = Quotation.find(params[:id])
    respond_to :html, :json
    if  @quotation.update_attributes(quotation_update_params)
      render :json => {
        file_content:  @quotation.message,
        file_error:  @quotation.errors,
        redirect: cart_url
      }
    else
      render :json => {
        file_content: @quotation.errors,
        status: :unprocessable_entity
      }
    end

  end

  private
    def get_customer_id_from_shopify
      connect_to_shopify
      customer = ShopifyAPI::Customer.search(query: 'email:'+params[:customer][:email])
      if customer.count >= 1
        return customer[0].id
      else
        return create_customer_at_shopify
      end
    end

  private
    def create_customer_at_shopify
      connect_to_shopify
      @customer = ShopifyAPI::Customer.new(customer_params.to_h)
      if @customer.save
        return @customer.id
      else
        render_new_quotation
        return
      end
    end

  private
    def quotation_params
      params.require(:quotation).permit(:message, :quantity, :yearly_quantity_id, :resize_image, :image_width, :image_height)
    end

  private
    def quotation_update_params
      params.require(:quotation).permit(:quantity, :return_file_format, :set_margin, :resize_image, :image_width, :image_height, :additional_comment, :product_variants, :total_price)
    end

  private
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email)
    end

  private
    def is_customer
      params[:customer_id].present? && !params[:customer_id].blank? ? true : false
    end

  private
    def get_logged_in_customer_id
      return params[:customer_id]
    end

  private
    def render_new_quotation
      render layout: 'guest', action: 'new', content_type: 'application/liquid'
    end

end

app/views/quotations/_form.html.erb
			<%= form_for @quotation, html: {class: "form-horizontal form-groups-bordered validate"} do |q| %>

				{% if customer %}
					<% if @customer.errors.any? || @quotation.errors.any? %>
						<div class="alert alert-danger">
							<strong>Please correct the following error(s) and try again:</strong>
							<ul>
							<% if @customer.errors.any? %>
								<% @customer.errors.full_messages.each do |msg| %>
			          				<li><%= msg %></li>
			        			<% end %>
		        			<% end %>
		        			<% if @quotation.errors.any? %>
								<% @quotation.errors.full_messages.each do |msg| %>
			          				<li><%= msg %></li>
			        			<% end %>
		        			<% end %>
							</ul>
						</div>
					<% end %>
				{% else %}
					<% if @quotation.errors.any? %>
						<div class="alert alert-danger">
							<strong>Please correct the following error(s) and try again:</strong>
							<ul>

		        			<% if @quotation.errors.any? %>
								<% @quotation.errors.full_messages.each do |msg| %>
			          				<li><%= msg %></li>
			        			<% end %>
		        			<% end %>
							</ul>
						</div>
					<% end %>
				{% endif %}


 			  	<%= fields_for @customer do |c| %>
	 			  	{% if customer %}
						<%= c.hidden_field(:customer_id, :value => "{{customer.id}}") %>
						<%= c.hidden_field(:first_name, :value => "{{ customer.first_name }}") %>
						<%= c.hidden_field(:last_name, :value => "{{ customer.last_name }}") %>
						<%= c.hidden_field(:email, :value => "{{customer.email}}") %>
					{% else %}
			    		<div class="form-group">
			    			<%= c.label(:first_name, "First name", class: "col-sm-5 control-label") %>
			    			<div class="col-sm-7">
			    				<%= c.text_field(:first_name, class: "form-control", placeholder: "John", "data-validate" => "required", "data-message-required" => "Please enter your first name.") %>
			    			</div>
			    		</div>

			    		<div class="form-group">
			    			<%= c.label(:last_name, "Last name", class: "col-sm-5 control-label") %>
			    			<div class="col-sm-7">
			    				<%= c.text_field(:last_name, class: "form-control", placeholder: "Doe", "data-validate" => "required", "data-message-required" => "Please enter your last name.") %>
			    			</div>
			    		</div>

			    		<div class="form-group">
			    			<%= c.label(:email, "E-mail", class: "col-sm-5 control-label") %>
			    			<div class="col-sm-7">
			    				<%= c.email_field(:email, class: "form-control", placeholder: "example@domain.com", "data-validate" => "required,email") %>
			    			</div>
			    		</div>

					{% endif %}
				<% end %>

		    		<div class="form-group">
		    			<%= q.label(:message, "Let us know what to do with your images", class: "col-sm-5 control-label") %>
		    			<div class="col-sm-7">
		    				<%= q.text_area :message, class: "form-control", "data-validate" => "required" %>
		    			</div>
		    		</div>

		    		<div class="form-group">
						<%= q.label(:quantity, "How many images should we provide a quote for?", class: "col-sm-5 control-label") %>
						<div class="col-sm-7">
							<div class="input-spinner">
								<button type="button" class="btn btn-default">-</button>
								<%= q.text_field(:quantity, class: "form-control size-1", data: {min: '1', max: '10000'}, "data-validate" => "number,required") %>
								<button type="button" class="btn btn-default">+</button>
							</div>
						</div>
					</div>

		    		<div class="form-group">
						<%= q.label(:yearly_quantity_id, "How many images do you need edited on a yearly basis?", class: "col-sm-5 control-label") %>
		    			<div class="col-sm-7">
							<%= q.collection_select(:yearly_quantity_id, YearlyQuantity.all, :id, :yearly_quantity_label, {:include_blank => 'Select..'}, {:class => "form-control",  "data-validate" => "required"}) %>
		    			</div>
		    		</div>

		    		<div class="form-group">
		    			<%= q.label(:resize_image, "Output image size", class: "col-sm-5 control-label") %>
		    			<div class="col-sm-7">
		    			    <p class="help-block">Resizing is free and we offer discount for choosing smaller image size, as they are quicker to process.</p>
		    				<div class="radio-inline">
		    					<label>
		    						<%= q.radio_button(:resize_image, "true", class:"controller-resize-image","data-validate" => "required","aria-describedby":"resize_image_message_error","aria-required":"false", "aria-invalid":"false") %>
		    						<%= q.label(:resize_image_1, 'Resize to') %>
		    					</label>
		    				</div>
		    				<div class="radio-inline">
		    					<label>
		    						<%= q.radio_button(:resize_image, "false",class:"controller-resize-image","data-validate" => "required","aria-describedby":"resize_image_message_error","aria-required":"false", "aria-invalid":"false") %>
		    						<%= q.label(:resize_image_0, 'Keep original size') %>
		    					</label>
		    				</div>
		    				<div><span id="resize_image_message_error" class="validate-has-error"></span></div>
		    				<br>
		    				<div id="quotation_group_height_width" class="form-inline nopadding has-resize-image hide">
		    					<div class="col-md-6 nopadding">
				    				<%= q.label(:image_width, "Width") %>
			                        <div class="input-group">
			                            <%= q.text_field(:image_width, size: 4,  class: "form-control quotation-resize-option", minlength: 1, maxlength: 4) %>
			                            <span class="input-group-addon">px</span>

									</div>
								</div>
								<div class="col-md-6 nopadding">
		                        <%= q.label(:image_height, "Height") %>
		                        <div class="input-group">
		                            <%= q.text_field(:image_height, size: 4, class: "form-control quotation-resize-option", minlength: 1, maxlength: 4) %>
		                            <span class="input-group-addon">px</span>



								</div>

								</div>
								 <div class="col-md-12 nopadding"><span id="resize_option_error_msg"></span></div>

							</div>
		    			</div>
		    		</div>

		    		<div class="form-group">
		    			<div class="col-sm-offset-5 col-sm-7">
		    				<%= q.submit("GET QUOTE", class: "btn btn-blue btn-lg") %>
		    			</div>
		    		</div>
		    	<% end %>

app/views/quotations/index.html.erb
<div class="page-header">
	<h3 class="text-uppercase">MY QUOTATIONS</h3>
</div>

<a href="<%=  new_quotation_path %>">
    <div class="btn btn-blue"><i class="entypo-plus"></i>NEW QUOTE</div>
</a>


<table class="table table-striped">
	<thead>
		<tr>
			<th>Quotation No.</th>
			<th>Date</th>
			<th>Services</th>
			<th>Amount</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
	    <% @quotations.each do |quotation| %>
    		<tr>
    			<td>#<%= link_to quotation.id, quotation_path(quotation.token) %></td>
    			<td><%= quotation.created_at %></td>
    			<td>
    				<% unless quotation.product_variants.blank? %>
	    				<% services = [] %>
	    				<% JSON.parse(quotation.product_variants).each do |variant| %>
	    					<% services.push variant['title'] %>
	    				<% end %>
	    				<%= services.join(', ') %>
    				<% end %>
    			</td>
    			<td>
    				<% unless quotation.total_price.blank? %>
    					$<%= quotation.total_price %>
    				<% end %>
				</td>
    			<td><div class="label label-info">{{ '<%= quotation.status %>' | upcase }}</div></td>
    		</tr>
		<% end %>
	</tbody>
</table>

app/views/quotations/new.html.erb
<div class="page-header">
	<h3>Get Your Quote in 45 Minutes</h3>
</div>

<div class="row">
    <div class="col-sm-12">

		<div class="panel panel-info" data-collapsed="0">
			<div class="panel-heading">
				<div class="panel-title">
					<strong>Please fill out the form below, and we'll get you a quote within 45 minutes.</strong>
				</div>
			</div>
			<div class="panel-body">

				<%= render 'form' %>

	    	</div>
    	</div>
    </div>
</div>

app/views/quotations/show.html.erb
<script>
	var shopUrl =  "{{shop.url}}";
</script>

<div class="page-header">
	<h3><%= I18n.t 'quotation.title' %></h3>
</div>

<div class="row">
	<div class="col-sm-12">
		<%
			if @quotation.status == 'new'
				@alert_style = 'alert-info'
				@badge_style = 'badge-info'
				@status_message = (I18n.t 'quotation.show.status_msg_new').html_safe
			elsif @quotation.status == 'ready'
				@alert_style = 'alert-success'
				@badge_style = 'badge-success'
				@status_message = (I18n.t 'quotation.show.status_msg_ready').html_safe
			else
				@alert_style = 'alert-default'
				@badge_style = 'badge-primary'
				@status_message = (I18n.t 'quotation.show.status_msg_completed').html_safe
			end
		%>
		<div class="alert <%= @alert_style %>">
			<p><strong><%= I18n.t 'quotation.show.status_l' %></strong>
				<span class="badge <%= @badge_style %>">
					<%= (@quotation.status.nil? ? 'nill' : @quotation.status.strip).titleize %>
				</span>
			</p>
			<p><%= @status_message %></p>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="col-sm-6 well">

			<%= (I18n.t 'quotation.show.customer.title').html_safe %> <br>
			<strong><%= @customer.first_name %> <%= @customer.last_name %></strong><br>
			<% if @customer.try(:default_address) %>
				<%= @customer.default_address.country_name %>
			<% end %>
		</div>
		<div class="col-sm-1">
		</div>
		<div class="col-sm-5 well text-right">
		    <%= I18n.t 'quotation.show.quotation_no_l'%><%= @quotation.id %><br>
			   <%= I18n.t 'quotation.show.quotation_created_date_l'%><%= @quotation.created_at.to_date %>
		</div>
	</div>
</div>

<div class="row" id='quotation-data'>
	<div class="col-sm-12">

		<div class="panel panel-info <%= 'disabled-section' if @quotation.status != 'ready' %>" data-collapsed="0">
			<div class="panel-heading">
				<h4 class="panel-title">
					<a data-toggle="collapse" data-parent="#accordion-test-1" href="#collapseOne-1" class="collapsed">
						<i class="entypo-clock"></i>
						  <%= I18n.t 'quotation.show.turnaround.title'%>
					</a>
				</h4>
			</div>
			<div class="panel-body">
				<%= form_for @quotation, html: {class: "form-horizontal form-groups-bordered validate edit_quotation" }, remote: true do |q| %>
				    <%= q.hidden_field(:product_variants) %>
				    <%= q.hidden_field(:total_price) %>
					<div class="form-group">
						<%= q.label(:turnaround, class: "col-sm-5 control-label") %>
						<div class="col-sm-7">
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "6") %>
		    						<span>6 Hours</span>
		    					</label>
		    				</div>
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "12") %>
		    						<span>12 Hours</span>
		    					</label>
		    				</div>
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "24") %>
		    						<span>24 Hours</span>
		    					</label>
		    				</div>
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "48") %>
		    						<span>48 Hours</span>
		    					</label>
		    				</div>
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "96") %>
		    						<span>96 Hours</span>
		    					</label>
		    				</div>
		    				<div class="radio turnaround">
		    					<label>
		    						<%= radio_button_tag(:trunaround, "168") %>
		    						<span>96+ Hours</span>
		    					</label>
		    				</div>
	    				</div>
					</div>

					<div class="form-group" id="prev-quote">
						<%= q.label(:quantity, class: "col-sm-5 control-label") %>
						<div class="col-sm-7">
							<div class="input-spinner">
								<button type="button" class="btn btn-default">-</button>
								<%= q.text_field(:quantity, class: "form-control size-1", data: {min: '1', max: '10000'}, "data-validate" => "number,required") %>
								<button type="button" class="btn btn-default">+</button>
							</div>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-sm-8">
							<div class="list-group" id="selc-service-items">
							</div>
							<p>
								<i>Original message:<br> 
									<% message = @quotation.message.split(' ') %>
									<% if message.length >= 10 %>
										<span id="part_quotaion_message">
											<% i = 0 %>
											<% while i < 10  do %>
											   <%= message[i] %> 
											   <% i +=1 %>
											<% end %>
											<a id="quotaion_message_more" >..more</a>
										</span>
										<span id="full_quotation_message">
											<%= @quotation.message %>
											<a id="quotaion_message_less" >..less</a>
										</span>
									<% else %>
										<%= @quotation.message %>
									<% end %>
								</i>
							</p>
							<%= q.hidden_field(:message) %>
							<%= q.hidden_field(:message_for_production) %>

						</div>
						<div class="col-sm-4 text-right">
							<div class="panel panel-success" data-collapsed="0">
								<div class="panel-body"  id='quotation-cart'>
								</div>
							</div>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="col-sm-12">
				    		<div class="form-group">
								<%= q.label(:return_file_format, "Return file format", class: "col-sm-5 control-label") %>
				    			<div class="col-sm-7">
									<%= q.select(:return_file_format, [['JPG'], ['PNG'], ['PSD'], ['TIFF']], {:include_blank => 'Select..'}, {:class => "form-control",  "data-validate" => "required"}) %>
				    			</div>
				    		</div>
				    		<div class="form-group">
				    			<div class="col-sm-offset-5 col-sm-7">
									<div class="checkbox">
										<label>
										    <%= q.check_box(:set_margin) %>
										Straighten, crop and set margin (FREE)
										</label>
										<a href="#"><small>Learn more</small></a>
									</div>
								</div>
				    		</div>
							<div class="form-group">
				    			<label class="col-sm-5 control-label">Output image size</label>
				    			<div class="col-sm-7">
				    				<div class="radio-inline">
				    					<label>
				    						<%= q.radio_button(:resize_image, "true", class:"controller-resize-image") %>
				    						<%= q.label(:resize_image_1, 'Resize to') %>
				    					</label>
				    				</div>
				    				<div class="radio-inline">
				    					<label>
				    						<%= q.radio_button(:resize_image, "false", class:"controller-resize-image") %>
				    						<%= q.label(:resize_image_0, 'Keep original size') %>
				    					</label>
				    				</div><br>
				    				<div id="quotation_group_height_width" class="form-inline has-resize-image hide">
					    				<%= q.label(:image_width, "Width") %>
				                        <div class="input-group">
				                            <%= q.text_field(:image_width, size: 4, class: "form-control", minlength: 1, maxlength: 4) %>
				                            <span class="input-group-addon">px</span>
										</div>
				                        <%= q.label(:image_height, "Height") %>
				                        <div class="input-group">
				                            <%= q.text_field(:image_height, size: 4, class: "form-control", minlength: 1, maxlength: 4) %>
				                            <span class="input-group-addon">px</span>
										</div>
									</div>
				    			</div>
				    		</div>

							<div class="form-group">
				    			<%= q.label(:additional_comment, "Additional comment (optional)", class: "col-sm-5 control-label") %>
				    			<div class="col-sm-7">
				    				<%= q.text_area :additional_comment, class: "form-control" %>
				    			</div>
				    		</div>

				    		<div class="form-group">
				    			<div class="col-sm-offset-5 col-sm-7">
				    				<%= q.submit("ADD TO CART", class: "btn btn-blue btn-lg", id:"edit_quotation") %>
				    			</div>
				    		</div>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

<ul>
 <% if @quotation.status != 'new' %>
<script>
    var product_variants 		= <%= @quotation.product_variants.html_safe %>;
    var quoteQuantity 			= <%= @quotation.quantity %>;
   	var quotationId 			= "<%= @quotation.id %>";
    var variants 				= <%= @variants.to_json.html_safe %>;
    var templateId 				= '';
    var messageForProduction 	= "<%= @quotation.message_for_production %>" ;
    var turnaround 				= <%= @turnaround.to_json.html_safe %>;
</script>

 <% end %>